runtests: Tweak output to make failing tests more obvious

diff --git a/runtests b/runtests
--- a/runtests
+++ b/runtests
@@ -36,6 +36,10 @@ fi
 
 code=0
 for rom in "${roms[@]}"; do
-	runtest "$rom" || code=1
+	if ! runtest "$rom"; then
+		echo "$rom failed!"
+		code=1
+	fi
+	echo
 done
 exit "$code"
